"""Render Brain + Model Router + 简单拼接 (Phase 3)。"""

from .assembly import (
    TARGET_MAX_SEC,
    TARGET_MIN_SEC,
    assemble_rough_cut,
    build_animatic_html,
    build_edl_text,
    build_vtt,
    concat_with_ffmpeg,
    export_cut,
)
from .backend import (
    BackendCapabilities,
    BaseAsyncRenderBackend,
    FatalRenderError,
    MediaSink,
    MockRenderBackend,
    PlaceholderMediaBackend,
    RenderBackend,
    RenderError,
    RenderRequest,
    RetryableRenderError,
    ffmpeg_available,
)
from .budget import (
    BudgetError,
    BudgetExceededError,
    BudgetGate,
    BudgetNotArmedError,
    DurationNotAllowedError,
    SubmissionNotConfirmedError,
    confirm_deny,
    confirm_interactive,
    confirm_yes,
)
from .kling_backend import KlingImageToVideoBackend, KlingTextToVideoBackend
from .registry import (
    BackendRegistry,
    kling_registry,
    mock_registry,
    placeholder_registry,
)
from .router import MODEL_REGISTRY, cost_summary, optimize_cost, route_shot
from .service import (
    MIN_IDENTITY_CONSISTENCY,
    MIN_SCENE_CONSISTENCY,
    RenderBrainService,
    RenderResult,
)

__all__ = [
    "RenderBrainService",
    "RenderResult",
    "RenderBackend",
    "RenderRequest",
    "BackendCapabilities",
    "MediaSink",
    "MockRenderBackend",
    "PlaceholderMediaBackend",
    "BaseAsyncRenderBackend",
    "BackendRegistry",
    "mock_registry",
    "placeholder_registry",
    "kling_registry",
    "KlingTextToVideoBackend",
    "KlingImageToVideoBackend",
    "BudgetGate",
    "BudgetError",
    "BudgetNotArmedError",
    "BudgetExceededError",
    "DurationNotAllowedError",
    "SubmissionNotConfirmedError",
    "confirm_deny",
    "confirm_yes",
    "confirm_interactive",
    "ffmpeg_available",
    "RenderError",
    "RetryableRenderError",
    "FatalRenderError",
    "route_shot",
    "optimize_cost",
    "cost_summary",
    "MODEL_REGISTRY",
    "assemble_rough_cut",
    "export_cut",
    "build_vtt",
    "build_edl_text",
    "build_animatic_html",
    "concat_with_ffmpeg",
    "TARGET_MIN_SEC",
    "TARGET_MAX_SEC",
    "MIN_IDENTITY_CONSISTENCY",
    "MIN_SCENE_CONSISTENCY",
]
